# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: crmne.Spotifast
PackageVersion: 0.11.0
InstallerType: inno
Scope: user
MinimumOSVersion: 10.0.0.0
InstallerSwitches:
  Silent: /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SP- /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
Protocols:
- spotify
ProductCode: '{FCED1EA0-EBF5-4C32-BA3B-A3AD724BACC3}_is1'
ReleaseDate: 2026-09-26
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\Programs\Spotifast'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/crmne/spotifast/releases/download/v0.11.0/spotifast-v0.11.0-x86_64-pc-windows-msvc-setup.exe
  InstallerSha256: D2C370342F08494F6C3A6B031AA3DAA09D5C4DBFEFFBB99C0424B4F1F00C27B6
- Architecture: arm64
  InstallerUrl: https://github.com/crmne/spotifast/releases/download/v0.11.0/spotifast-v0.11.0-aarch64-pc-windows-msvc-setup.exe
  InstallerSha256: 2A657A5DAF862E68FA64E1487FFF573E85280D44D4B91865B365AE890CBED955
ManifestType: installer
ManifestVersion: 1.12.0
